spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
        web-admin-password: passw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default